name: Tu_Cloud_Gaming_FULL_VERSION
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Lay code ve
        uses: actions/checkout@v4

      - name: 2. Ket noi Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: 3. Cai dat Giao dien & RDP (De dang nhap tu Windows)
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          # Dong lenh quan trong nhat: Thiet lap User va Password
          sudo useradd -m runneradmin
          sudo adduser runneradmin sudo
          echo "runneradmin:TuCloud123" | sudo chpasswd
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/xrdp/Xwrapper.config
          sudo systemctl restart xrdp
          echo "He thong da san sang!"

      - name: 4. Giu may ao khong bi tat (Trong 6 tieng)
        run: sleep 21600
